version: "3"
services:
  webapp:
    image: myrailsapp
    depends_on:
      - mysql
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ".:/app:cached"
    tmpfs:
      - /tmp
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    environment:
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysql
      LANG: en_US.UTF-8
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
      LANG: en_US.UTF-8
    volumes:
      - "./mysql/data:/var/lib/mysql:cached"
    ports:
      - "3306:3306"
