version: "3"
services:
  webapp:
    image: myrailsapp
    ports:
      - "3000:3000"
    volumes:
      - ".:/app:cached"
    tmpfs:
      - /tmp
    command: bundle exec rails s -b 0.0.0.0
    environment:
      - "LANG=en_US.UTF-8"
