/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * User API
 * API for managing users
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  GetUsersResponse
} from '.././model';


export const getGetApiUsersResponseMock = (overrideResponse: Partial< GetUsersResponse > = {}): GetUsersResponse => ({users: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.string.alpha({length: {min: 10, max: 20}})})), ...overrideResponse})


export const getGetApiUsersMockHandler = (overrideResponse?: GetUsersResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetUsersResponse> | GetUsersResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/users', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiUsersResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getUsersMock = () => [
  getGetApiUsersMockHandler()
]
